version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  main-test:
    docker:
      - image: circleci/node:10.8.0
    working_directory: ~/Turtle/front-end
workflows:
  node-tests:
    jobs:
      - main-test
      - node/test
